# serverless.yml

service: serverless-nodejs-app

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  timeout: 15


  
functions:
  app:
    handler: handler.hello # reference the file and exported method
    events: # events trigger lambda functions
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: true
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true

